### ISSUE TITLE
Simple installation is not working?

### ISSUE THREAD

**Issue by miguelchico** [voznik/ngx-odm#59]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/voznik/ngx-odm/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Installing library following documentation doesn't work

## Expected behavior

Installation is possible

## Minimal reproduction of the problem with instructions

- Create a simple angular project using NX or Angular CLI
- npm install @ngx-odm/rxdb
- try to import 
import { provideRxDatabase } from '@ngx-odm/rxdb';
import { getRxDatabaseCreator } from '@ngx-odm/rxdb/config';
- Start project

## What is the motivation / use case for changing the behavior?

Using library should work

## Environment

<pre><code>
Libs:
- @angular/core version: 17.0.2
- @ngx-odm/rxdb version: 5.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 20.10
- Platform:  Mac

Others:
Checking node_modules I can see source code of the project rather than packaged libraries

</code></pre>
![image](https://github.com/voznik/ngx-odm/assets/6106661/66ce3851-591a-4563-8b24-8c9c84d72097)

**Comment by voznik** [comment]
Thanks for reporting this issue. Latest release needs to be re-published to npm, working on it!

**Comment by miguelchico** [comment]
Great, thank you for letting me know

**Comment by voznik** [comment]
fixed with publishing version 5.2.0
